version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
          - "com.google.devtools.ksp"
        update-types:
          - "minor"
          - "patch"
      androidx:
        patterns:
          - "androidx.*"
        update-types:
          - "minor"
          - "patch"
      hilt:
        patterns:
          - "com.google.dagger*"
          - "androidx.hilt*"
        update-types:
          - "minor"
          - "patch"
      compose:
        patterns:
          - "androidx.compose*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "junit"
          - "org.jetbrains.kotlinx*"
          - "app.cash.turbine"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
