minimum_pre_commit_version: 3.7.0

repos:
  - repo: local
    hooks:
      - id: pratoo-quality-check
        name: pratoo quality check
        entry: ./gradlew qualityCheck
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  - repo: https://github.com/conventional-commits/commitlint-pre-commit-hook
    rev: v1.4.1
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/config-conventional"
