package com.diaszano.pratoo.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF825500)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB2)
val md_theme_light_onPrimaryContainer = Color(0xFF291800)
val md_theme_light_secondary = Color(0xFF6F5B40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFADEBC)
val md_theme_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_light_tertiary = Color(0xFF51643C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4EAB7)
val md_theme_light_onTertiaryContainer = Color(0xFF102000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF0E0D0)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)

val md_theme_dark_primary = Color(0xFFFEBF28)
val md_theme_dark_onPrimary = Color(0xFF452B00)
val md_theme_dark_primaryContainer = Color(0xFF634000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB2)
val md_theme_dark_secondary = Color(0xFFDDC3A1)
val md_theme_dark_onSecondary = Color(0xFF3E2E16)
val md_theme_dark_secondaryContainer = Color(0xFF56442A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFADEBC)
val md_theme_dark_tertiary = Color(0xFFB8CE9D)
val md_theme_dark_onTertiary = Color(0xFF253512)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C27)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4EAB7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEBE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEBE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B4)
